In [1]:
from mibici.pipeline import load_stage

datos = load_stage("raw", nrows=5)

viajes = datos["viajes"]
estaciones = datos["estaciones"]

display(viajes)
display(estaciones.head())

2026-10-16 23:48:41.191 | INFO     | mibici.config:<module>:11 - PROJ_ROOT path is: /home/jovyan/notebooks/mibici/mibici_predictions

,Viaje_Id,Usuario_Id,Genero,Año_de_nacimiento,Inicio_del_viaje,Fin_del_viaje,Origen_Id,Destino_Id
0,45255658,4710104,F,1968,2026-08-01 00:00:33,2026-08-01 00:09:03,156,17
1,45255659,4600206,NaN,1997,2026-08-01 00:00:36,2026-08-01 00:08:35,49,280
2,45255660,4636456,M,2002,2026-08-01 00:00:41,2026-08-01 00:04:56,322,487
3,45255661,355515,M,1992,2026-08-01 00:01:04,2026-08-01 00:06:26,42,38
4,45255662,4616345,M,2006,2026-08-01 00:01:29,2026-08-01 00:07:21,161,179
5,45705294,4722545,M,1997,2026-09-01 00:00:59,2026-09-01 00:18:55,283,49
6,45705295,2344334,M,2004,2026-09-01 00:01:36,2026-09-01 00:17:52,67,383
7,45705301,4454420,M,2001,2026-09-01 00:03:36,2026-09-01 00:19:31,395,357
8,45705303,4512715,M,1996,2026-09-01 00:03:59,2026-09-01 00:07:07,371,57
9,45705304,2765763,M,2002,2026-09-01 00:04:09,2026-09-01 00:30:19,357,80

,id,name,latitude,longitude,dpcapacity
0,2,(GDL-001) C. Epigmenio Glez./ Av. 16 de Sept.,20.666378,-103.348820,15
1,3,(GDL-002) C. Colonias / Av. Niños héroes,20.667228,-103.366000,15
2,4,(GDL-003) C. Vidrio / Av. Chapultepec,20.667690,-103.368252,19
3,5,(GDL-004) C. Ghilardi /C. Miraflores,20.691847,-103.362549,19
4,6,(GDL-005) C. San Diego /Calzada Independencia,20.681158,-103.339363,11